### ISSUE TITLE
Retry connections to redis

### ISSUE THREAD

**Issue by markrcote** [markrcote/ledweb#3]
In particular, on boot up redis may not be up and running yet. ledservice needs to retry the connection instead of just failing.

**Comment by markrcote** [comment]
Traceback:

```
Sep  2 14:45:27 pi3 python[343]: Traceback (most recent call last):
Sep  2 14:45:27 pi3 python[343]:   File "/home/pi/ledweb/ledservicevenv/lib/python3.5/site-packages/redis/connection.py", line 492, in connect
Sep  2 14:45:27 pi3 python[343]:     sock = self._connect()
Sep  2 14:45:27 pi3 python[343]:   File "/home/pi/ledweb/ledservicevenv/lib/python3.5/site-packages/redis/connection.py", line 550, in _connect
Sep  2 14:45:27 pi3 python[343]:     raise err
Sep  2 14:45:27 pi3 python[343]:   File "/home/pi/ledweb/ledservicevenv/lib/python3.5/site-packages/redis/connection.py", line 538, in _connect
Sep  2 14:45:27 pi3 python[343]:     sock.connect(socket_address)
Sep  2 14:45:27 pi3 python[343]: ConnectionRefusedError: [Errno 111] Connection refused
Sep  2 14:45:27 pi3 python[343]: During handling of the above exception, another exception occurred:
Sep  2 14:45:27 pi3 python[343]: Traceback (most recent call last):
Sep  2 14:45:27 pi3 python[343]:   File "ledservice.py", line 271, in <module>
Sep  2 14:45:27 pi3 python[343]:     main()
Sep  2 14:45:27 pi3 python[343]:   File "ledservice.py", line 267, in main
Sep  2 14:45:27 pi3 python[343]:     led_service.loop()
Sep  2 14:45:27 pi3 python[343]:   File "ledservice.py", line 235, in loop
Sep  2 14:45:27 pi3 python[343]:     while self.redis_cli.llen(options.REDIS_QUEUE) == 0:
Sep  2 14:45:27 pi3 python[343]:   File "/home/pi/ledweb/ledservicevenv/lib/python3.5/site-packages/redis/client.py", line 1603, in llen
Sep  2 14:45:27 pi3 python[343]:     return self.execute_command('LLEN', name)
Sep  2 14:45:27 pi3 python[343]:   File "/home/pi/ledweb/ledservicevenv/lib/python3.5/site-packages/redis/client.py", line 772, in execute_command
Sep  2 14:45:27 pi3 python[343]:     connection = pool.get_connection(command_name, **options)
Sep  2 14:45:27 pi3 python[343]:   File "/home/pi/ledweb/ledservicevenv/lib/python3.5/site-packages/redis/connection.py", line 994, in get_connection
Sep  2 14:45:27 pi3 python[343]:     connection.connect()
Sep  2 14:45:27 pi3 python[343]:   File "/home/pi/ledweb/ledservicevenv/lib/python3.5/site-packages/redis/connection.py", line 497, in connect
Sep  2 14:45:27 pi3 python[343]:     raise ConnectionError(self._error_message(e))
Sep  2 14:45:27 pi3 python[343]: redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
```
